# Generated by Django 5.0.6 on 2024-05-26 13:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('concat_fields', models.TextField(unique=True)),
                ('name', models.TextField(max_length=255)),
                ('type', models.TextField(max_length=255)),
                ('director', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
