# Generated by Django 5.0.6 on 2024-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
