# Generated by Django 5.0.6 on 2024-08-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_zone_commune_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='number',
        ),
    ]
