# Generated by Django 5.0.6 on 2024-08-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_name_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='nunicipality',
            new_name='municipality',
        ),
    ]
