# Generated by Django 5.0.6 on 2024-08-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_nunicipality_commune_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fullnameFather',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fullnameMother',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phoneTwo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='referencePoint',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='neighborhood',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
