# Generated by Django 5.0.6 on 2024-06-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='province',
        ),
    ]
